#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Core stuff
cookbook 'apt'
cookbook 'build-essential'

# Setup a ruby environment
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv', :ref => 'v0.6.4'

# Database business
cookbook 'mysql'
cookbook 'initdb', :git => 'git://github.com/xforty/chef-initdb.git'

# Rails server
cookbook 'nginx'
cookbook 'unicorn'
cookbook 'runit'

# Glue it all together
cookbook 'rails-lastmile', :git => 'git://github.com/alexbain/rails-lastmile.git'
