#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Core
cookbook 'apt'
cookbook 'build-essential'

# Ruby
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv', :ref => 'v0.6.4'

# Database
cookbook 'mysql'

# Rails Server
cookbook 'nginx'
cookbook 'unicorn'
cookbook 'runit'

# Glue / Init
cookbook 'rails-lastmile', :git => 'git://github.com/alexbain/rails-lastmile.git'
